import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final _localized = <String, Map<String, String>>{
    'en': {
      'languageTitle': 'Choose app language',
      'languageSubtitle': 'Pick once before onboarding. You can change it later from Profile.',
      'continue': 'Continue',
      'onboardingSkip': 'Skip',
      'onboardingNext': 'Next',
      'onboardingStart': 'Get Started',
      'onboardFarmTitle': 'Manage Your Farm Digitally',
      'onboardFarmBody': 'Track crops, soil, irrigation, harvests and farm performance from one place.',
      'onboardAiTitle': 'AI Farming Assistant',
      'onboardAiBody': 'Get smart recommendations, disease assistance and farming guidance in your language.',
      'onboardCoopTitle': 'Sell Smarter Together',
      'onboardCoopBody': 'Join nearby farmers, reduce transportation costs and find better selling opportunities.',
      'home': 'Home',
      'farm': 'Farm',
      'ai': 'AI',
      'market': 'Market',
      'profile': 'Profile',
      'search': 'Search',
      'notifications': 'Notifications',
      'goodMorning': 'Good Morning',
      'village': 'Village',
      'farmHealth': 'Farm Health',
      'quickActions': 'Quick Actions',
      'askAi': 'Ask AI',
      'scan': 'Scan',
      'harvest': 'Harvest',
      'sell': 'Sell',
      'coop': 'Co-op',
      'truck': 'Truck',
      'schemes': 'Schemes',
      'reports': 'Reports',
      'currentCrop': 'Current Crop',
      'smartInsights': 'Smart Insights',
      'marketPrices': 'Market Prices',
      'upcomingTasks': 'Upcoming Tasks',
      'profileSettings': 'Profile & Settings',
      'editProfile': 'Edit Profile',
      'farmerDetails': 'Farmer Details',
      'farmSummary': 'Farm Summary',
      'settings': 'Settings',
      'language': 'Language',
      'governmentSchemes': 'Government Schemes',
      'analytics': 'Analytics',
      'myFarms': 'My Farms',
      'smartCooperative': 'Smart Cooperative',
      'sharedTransportation': 'Shared Transportation',
    },
    'hi': {
      'languageTitle': 'ऐप भाषा चुनें',
      'languageSubtitle': 'ऑनबोर्डिंग से पहले भाषा चुनें। बाद में प्रोफाइल से बदल सकते हैं।',
      'continue': 'जारी रखें',
      'onboardingSkip': 'छोड़ें',
      'onboardingNext': 'आगे',
      'onboardingStart': 'शुरू करें',
      'onboardFarmTitle': 'अपने खेत को डिजिटल रूप से संभालें',
      'onboardFarmBody': 'फसल, मिट्टी, सिंचाई, कटाई और प्रदर्शन एक जगह देखें।',
      'onboardAiTitle': 'AI खेती सहायक',
      'onboardAiBody': 'अपनी भाषा में सुझाव, रोग सहायता और खेती मार्गदर्शन पाएं।',
      'onboardCoopTitle': 'मिलकर बेहतर बेचें',
      'onboardCoopBody': 'नजदीकी किसानों से जुड़ें, परिवहन खर्च घटाएं और बेहतर बिक्री पाएं।',
      'home': 'होम',
      'farm': 'खेत',
      'ai': 'AI',
      'market': 'बाजार',
      'profile': 'प्रोफाइल',
      'search': 'खोजें',
      'notifications': 'सूचनाएं',
      'goodMorning': 'सुप्रभात',
      'village': 'गांव',
      'farmHealth': 'खेत स्वास्थ्य',
      'quickActions': 'त्वरित कार्य',
      'askAi': 'AI से पूछें',
      'scan': 'स्कैन',
      'harvest': 'कटाई',
      'sell': 'बेचें',
      'coop': 'समूह',
      'truck': 'ट्रक',
      'schemes': 'योजनाएं',
      'reports': 'रिपोर्ट',
      'currentCrop': 'मौजूदा फसल',
      'smartInsights': 'स्मार्ट जानकारी',
      'marketPrices': 'बाजार भाव',
      'upcomingTasks': 'आने वाले काम',
      'profileSettings': 'प्रोफाइल और सेटिंग',
      'editProfile': 'प्रोफाइल संपादित करें',
      'farmerDetails': 'किसान विवरण',
      'farmSummary': 'खेत सारांश',
      'settings': 'सेटिंग',
      'language': 'भाषा',
      'governmentSchemes': 'सरकारी योजनाएं',
      'analytics': 'विश्लेषण',
      'myFarms': 'मेरे खेत',
      'smartCooperative': 'स्मार्ट सहकारी',
      'sharedTransportation': 'साझा परिवहन',
      'Agro AI': 'एग्रो AI',
      'Login': 'लॉगिन',
      'Register': 'रजिस्टर',
      'Create Account': 'खाता बनाएं',
      'Reset Password': 'पासवर्ड रीसेट',
      'Email': 'ईमेल',
      'Password': 'पासवर्ड',
      'Phone': 'फोन',
      'Full Name': 'पूरा नाम',
      'Email or Mobile Number': 'ईमेल या मोबाइल नंबर',
      'Send OTP': 'OTP भेजें',
      'Preferred Language': 'पसंदीदा भाषा',
      'Farm Name': 'खेत का नाम',
      'Land Size': 'भूमि आकार',
      'Area Unit': 'क्षेत्र इकाई',
      'Farm Location / GPS': 'खेत स्थान / GPS',
      'Current Crop': 'मौजूदा फसल',
      'Predicted Yield Tonnes': 'अनुमानित उत्पादन टन',
      'Soil Type': 'मिट्टी का प्रकार',
      'Soil Health Score': 'मिट्टी स्वास्थ्य स्कोर',
      'Crop Health Score': 'फसल स्वास्थ्य स्कोर',
      'Water Source': 'जल स्रोत',
      'Irrigation Type': 'सिंचाई प्रकार',
      'Previous Crop': 'पिछली फसल',
      'Previous Season': 'पिछला मौसम',
      'Previous Yield Tonnes': 'पिछला उत्पादन टन',
      'Previous Revenue': 'पिछला राजस्व',
      'Latest Yield Quantity kg': 'नया उत्पादन किलो',
      'Selling Price per kg': 'प्रति किलो बिक्री भाव',
      'Buyer / Market Name': 'खरीदार / बाजार नाम',
      'Transportation Cost': 'परिवहन खर्च',
      'Labour Cost': 'मजदूरी खर्च',
      'Other Expenses': 'अन्य खर्च',
      'Create Digital Twin': 'डिजिटल ट्विन बनाएं',
      'Farmer Profile': 'किसान प्रोफाइल',
      'Farm Details': 'खेत विवरण',
      'Soil Information': 'मिट्टी जानकारी',
      'Irrigation Details': 'सिंचाई विवरण',
      'Crop History': 'फसल इतिहास',
      'Yield Records': 'उत्पादन रिकॉर्ड',
      'Farm Analytics': 'खेत विश्लेषण',
      'Farm Digital Twin': 'फार्म डिजिटल ट्विन',
      'Add Farm': 'खेत जोड़ें',
      'Total Farm Area': 'कुल खेत क्षेत्र',
      'Active Crops': 'सक्रिय फसलें',
      'Soil Health': 'मिट्टी स्वास्थ्य',
      'Predicted Yield': 'अनुमानित उत्पादन',
      'Farm Cards': 'खेत कार्ड',
      'Farm Modules': 'खेत मॉड्यूल',
      'No farms added yet': 'अभी कोई खेत नहीं जोड़ा गया',
      'Add your first farm to start receiving personalised AI recommendations.': 'व्यक्तिगत AI सुझाव पाने के लिए पहला खेत जोड़ें।',
      'Delete Farm': 'खेत हटाएं',
      'Save Farm': 'खेत सेव करें',
      'Unit': 'इकाई',
      'Location': 'स्थान',
      'Crop Filter': 'फसल फिल्टर',
      'Recommended Fertilizer': 'अनुशंसित उर्वरक',
      'Get Fertilizer Recommendation': 'उर्वरक सुझाव पाएं',
      'Irrigation': 'सिंचाई',
      'Last Irrigation': 'पिछली सिंचाई',
      'Next Irrigation': 'अगली सिंचाई',
      'Water Used': 'जल उपयोग',
      'Rain Forecast': 'बारिश अनुमान',
      'Log Irrigation': 'सिंचाई दर्ज करें',
      'Save Yield Record': 'उत्पादन रिकॉर्ड सेव करें',
      'Analytics Dashboard': 'विश्लेषण डैशबोर्ड',
      'Price Trends': 'भाव रुझान',
      'Sales Analytics': 'बिक्री विश्लेषण',
      'Profit & Loss Graphs': 'लाभ और नुकसान ग्राफ',
      'Risk Dashboard': 'जोखिम डैशबोर्ड',
      'Demand Heatmaps': 'मांग हीटमैप',
      'Buyer Analytics': 'खरीदार विश्लेषण',
      'Finance Summary': 'वित्त सारांश',
      'Revenue': 'राजस्व',
      'Expenses': 'खर्च',
      'Profit': 'लाभ',
      'Margin': 'मार्जिन',
      'Weather Risk': 'मौसम जोखिम',
      'Disease Risk': 'रोग जोखिम',
      'Market Risk': 'बाजार जोखिम',
      'Finance Risk': 'वित्त जोखिम',
      'LOW': 'कम',
      'MEDIUM': 'मध्यम',
      'HIGH': 'ऊंचा',
      'Sold': 'बिक गया',
      'Smart Harvest Planner': 'स्मार्ट कटाई प्लानर',
      'Harvest Calendar': 'कटाई कैलेंडर',
      'Crop Status': 'फसल स्थिति',
      'Weather Data': 'मौसम डेटा',
      'Market Data': 'बाजार डेटा',
      'Harvest Analysis': 'कटाई विश्लेषण',
      'Best Harvest Window': 'सबसे अच्छा कटाई समय',
      'AI Pick': 'AI चयन',
      'AI best harvest window': 'AI सुझाया श्रेष्ठ कटाई समय',
      'Farm': 'खेत',
      'Crop Health': 'फसल स्वास्थ्य',
      'Expected Yield': 'अपेक्षित उत्पादन',
      'Expected Harvest': 'अपेक्षित कटाई',
      'Primary Farm': 'मुख्य खेत',
      'Soon': 'जल्द',
      'Selected': 'चयनित',
      'Avoid': 'बचें',
      'Labour Planning': 'मजदूर योजना',
      'Truck Availability': 'ट्रक उपलब्धता',
      'Buyer Schedule Management': 'खरीदार समय प्रबंधन',
      'No truck available': 'कोई ट्रक उपलब्ध नहीं',
      'Buyer pool open': 'खरीदार पूल खुला',
      'Schedule': 'शेड्यूल करें',
      'Confirm Buyer': 'खरीदार पक्का करें',
      'Scheduled Plans': 'शेड्यूल प्लान',
      'Scan Crop': 'फसल स्कैन',
      'Take Photo': 'फोटो लें',
      'Gallery': 'गैलरी',
      'Analysing crop...': 'फसल विश्लेषण हो रहा है...',
      'No scan yet': 'अभी कोई स्कैन नहीं',
      'Upload or capture a crop photo to get AI disease guidance.': 'AI रोग मार्गदर्शन के लिए फसल फोटो लें या अपलोड करें।',
      'Start Scan': 'स्कैन शुरू करें',
      'Disease Detection': 'रोग पहचान',
      'Treatment Guidance': 'उपचार मार्गदर्शन',
      'Confidence': 'विश्वास',
      'Agro AI is analysing farm context...': 'एग्रो AI खेत संदर्भ का विश्लेषण कर रहा है...',
      'Your personal farming assistant': 'आपका व्यक्तिगत खेती सहायक',
      'Listening... speak now': 'सुन रहा है... अब बोलें',
      'Ask Agro AI...': 'एग्रो AI से पूछें...',
      'Microphone permission is needed for voice chat.': 'वॉइस चैट के लिए माइक्रोफोन अनुमति चाहिए।',
      'Government Schemes': 'सरकारी योजनाएं',
      'Search schemes': 'योजनाएं खोजें',
      'All': 'सभी',
      'Central Government': 'केंद्र सरकार',
      'State Government': 'राज्य सरकार',
      'Loans': 'ऋण',
      'Insurance': 'बीमा',
      'Equipment': 'उपकरण',
      'Subsidies': 'सब्सिडी',
      'Deadline': 'अंतिम तारीख',
      'Eligibility': 'पात्रता',
      'Benefit': 'लाभ',
      'Check': 'चेक',
      'Save': 'सेव',
      'Portal': 'पोर्टल',
      'Cooperative & Marketplace': 'सहकारी और बाजार',
      'Market Prices / Produce Listing': 'बाजार भाव / उत्पादन सूची',
      'Join Cooperative': 'सहकारी से जुड़ें',
      'Shared Logistics': 'साझा लॉजिस्टिक्स',
      'Sell / Schedule Pickup': 'बेचें / पिकअप शेड्यूल',
      'Automatic Farmer Grouping': 'स्वचालित किसान समूह',
      'Shared Transportation': 'साझा परिवहन',
      'Route Optimization': 'मार्ग अनुकूलन',
      'Transportation Cost Splitting': 'परिवहन खर्च बांटना',
      'Joint Selling': 'सामूहिक बिक्री',
      'Truck Allocation': 'ट्रक आवंटन',
      'Pickup Scheduling': 'पिकअप शेड्यूल',
      'Upcoming Pickup': 'आने वाला पिकअप',
      'Cost Splitting': 'खर्च विभाजन',
      'Accept': 'स्वीकार',
      'Reject': 'अस्वीकार',
      'Counter': 'काउंटर',
      'Global Search': 'वैश्विक खोज',
      'Search crops, buyers, schemes...': 'फसल, खरीदार, योजनाएं खोजें...',
      'Notifications': 'सूचनाएं',
      'No active crop': 'कोई सक्रिय फसल नहीं',
      'Add a farm digital twin to track crop progress.': 'फसल प्रगति देखने के लिए फार्म डिजिटल ट्विन जोड़ें।',
      'GOOD': 'अच्छा',
      'Fertilizer Alert': 'उर्वरक अलर्ट',
      'Weather Alert': 'मौसम अलर्ट',
      'Market Alert': 'बाजार अलर्ट',
      'Harvest Alert': 'कटाई अलर्ट',
      'Market Prices': 'बाजार भाव',
      'Upcoming Tasks': 'आने वाले काम',
      'AgroPredict AI: Farm smarter, sell better': 'एग्रोप्रेडिक्ट AI: बेहतर खेती, बेहतर बिक्री',
      'Welcome back': 'वापस स्वागत है',
      'Manage your farm intelligence in demo mode.': 'डेमो मोड में अपनी खेती इंटेलिजेंस संभालें।',
      'Forgot Password?': 'पासवर्ड भूल गए?',
      'Create Farmer Account': 'किसान खाता बनाएं',
      'Minimum 6 characters': 'कम से कम 6 अक्षर',
      'Mobile Number': 'मोबाइल नंबर',
      'District': 'जिला',
      'Enter a valid number': 'मान्य नंबर दर्ज करें',
      'Farmer & Farm Setup': 'किसान और खेत सेटअप',
      'Yield Records & Analytics': 'उत्पादन रिकॉर्ड और विश्लेषण',
      'English': 'अंग्रेजी',
      'Hindi': 'हिन्दी',
      'Marathi': 'मराठी',
      'Gujarati': 'गुजराती',
      'Tamil': 'तमिल',
      'Telugu': 'तेलुगु',
      'Kannada': 'कन्नड़',
      'Punjabi': 'पंजाबी',
      'acre': 'एकड़',
      'hectare': 'हेक्टेयर',
      'Well': 'कुआं',
      'Borewell': 'बोरवेल',
      'Canal': 'नहर',
      'River': 'नदी',
      'Rainwater': 'वर्षा जल',
      'Other': 'अन्य',
      'Drip': 'ड्रिप',
      'Sprinkler': 'स्प्रिंकलर',
      'Flood': 'बाढ़ सिंचाई',
      'Rain-fed': 'वर्षा आधारित',
      'Required': 'आवश्यक',
      'OTP-ready reset flow prepared for Firebase Authentication.': 'Firebase Authentication के लिए OTP रीसेट फ्लो तैयार है।',
      'Total Land': 'कुल भूमि',
      'Total Farms': 'कुल खेत',
      'Current Season': 'मौजूदा मौसम',
      'Help & Support': 'सहायता',
      'About AgroPredict': 'AgroPredict के बारे में',
      'Logout': 'लॉगआउट',
      'Farmer ID': 'किसान ID',
      'Save Changes': 'बदलाव सेव करें',
      'Soil': 'मिट्टी',
      'Crop': 'फसल',
      'Map-ready location': 'मैप के लिए तैयार स्थान',
      'acres': 'एकड़',
      'Yield': 'उत्पादन',
      'tonnes': 'टन',
      'Optimal': 'उत्तम',
      'Low': 'कम',
      'pH Optimal': 'pH उत्तम',
      'Nitrogen Low': 'नाइट्रोजन कम',
      'Phosphorus Optimal': 'फॉस्फोरस उत्तम',
      'Potassium Optimal': 'पोटैशियम उत्तम',
      'Moisture Optimal': 'नमी उत्तम',
      'Organic Carbon Low': 'ऑर्गेनिक कार्बन कम',
      'AI Insight: Nitrogen levels are below the recommended range for your tomato crop.': 'AI सुझाव: टमाटर फसल के लिए नाइट्रोजन स्तर अनुशंसित सीमा से कम है।',
      'Urea: 18 kg/acre, DAP: 10 kg/acre, Potash: 12 kg/acre, Organic Compost: 600 kg/acre. Apply after light irrigation and avoid expected rainfall. Estimated cost: Rs 4,850.': 'यूरिया: 18 किलो/एकड़, DAP: 10 किलो/एकड़, पोटाश: 12 किलो/एकड़, जैविक खाद: 600 किलो/एकड़। हल्की सिंचाई के बाद डालें और बारिश से बचें। अनुमानित खर्च: Rs 4,850।',
      '2 days': '2 दिन',
      'Tomorrow': 'कल',
      'Irrigation logged. Next recommendation updated.': 'सिंचाई दर्ज हुई। अगला सुझाव अपडेट हुआ।',
      'Quantity kg': 'मात्रा किलो',
      'Gross Revenue': 'सकल राजस्व',
      'Total Expenses': 'कुल खर्च',
      'Net Profit': 'शुद्ध लाभ',
      'Profit Margin': 'लाभ मार्जिन',
      'Tomato': 'टमाटर',
      'Onion': 'प्याज',
      'Hybrid': 'हाइब्रिड',
      'Quantity tonnes': 'मात्रा टन',
      'Price per kg': 'प्रति किलो भाव',
      'Quality Grade': 'गुणवत्ता ग्रेड',
      'Create Listing': 'लिस्टिंग बनाएं',
      'Your Listings': 'आपकी लिस्टिंग',
      'No crop listings': 'कोई फसल लिस्टिंग नहीं',
      'Create a sale listing so verified buyers can discover your produce.': 'बिक्री लिस्टिंग बनाएं ताकि सत्यापित खरीदार आपकी उपज देख सकें।',
      'Create Above': 'ऊपर बनाएं',
      'Buyers': 'खरीदार',
      'Orders': 'ऑर्डर',
      'Prices': 'भाव',
      'Grade': 'ग्रेड',
      'Buying': 'खरीद',
      'Quantity': 'मात्रा',
      'Distance': 'दूरी',
      'Offer': 'ऑफर',
      'View': 'देखें',
      'Negotiate': 'बातचीत',
      'Offer accepted from': 'ऑफर स्वीकार किया गया',
      'FreshKart Foods': 'फ्रेशकर्ट फूड्स',
      'Confirmed': 'पक्का',
      'Pickup': 'पिकअप',
      'March': 'मार्च',
      'Nearby Markets': 'नजदीकी बाजार',
      'Flow': 'फ्लो',
      'Automatic Grouping': 'स्वचालित समूह',
      'Shared Transport': 'साझा परिवहन',
      'Open Co-op': 'Co-op खोलें',
      'Transport': 'परिवहन',
      'Shared Logistics & Truck Allocation': 'साझा लॉजिस्टिक्स और ट्रक आवंटन',
      'Route Optimization & Cost Splitting': 'मार्ग अनुकूलन और खर्च विभाजन',
      'Modules 16 + 17 Merged': 'मॉड्यूल 16 + 17 मर्ज',
      'Marketplace': 'बाजार',
      'Logistics': 'लॉजिस्टिक्स',
      'Join Group': 'समूह में जुड़ें',
      'No live price found for': 'लाइव भाव नहीं मिला',
      'best nearby price': 'सबसे अच्छा नजदीकी भाव',
      'at': 'पर',
      'Create a produce listing before cooperative matching.': 'सहकारी मैचिंग से पहले उत्पादन लिस्टिंग बनाएं।',
      'Listed': 'लिस्टेड',
      'Joined': 'जुड़ गए',
      'Recommended': 'अनुशंसित',
      'Join': 'जुड़ें',
      'Crop match': 'फसल मेल',
      'Harvest window': 'कटाई समय',
      'Route fit': 'मार्ग फिट',
      'Buyer demand': 'खरीदार मांग',
      'Shared load': 'साझा लोड',
      'to': 'तक',
      'Optimized route': 'अनुकूलित मार्ग',
      'Open Logistics Plan': 'लॉजिस्टिक्स प्लान खोलें',
      'Verified buyer pool': 'सत्यापित खरीदार पूल',
      'Joint selling crop': 'सामूहिक बिक्री फसल',
      'Individual offer': 'व्यक्तिगत ऑफर',
      'Group negotiated offer': 'समूह तय ऑफर',
      'Extra revenue': 'अतिरिक्त राजस्व',
      'Joint selling offer accepted.': 'सामूहिक बिक्री ऑफर स्वीकार हुआ।',
      'Pickup schedule confirmed.': 'पिकअप शेड्यूल पक्का हुआ।',
      'Grouping Score': 'समूह स्कोर',
      'Transport Saving': 'परिवहन बचत',
      'Extra Revenue': 'अतिरिक्त राजस्व',
      'Truck': 'ट्रक',
      'Capacity': 'क्षमता',
      'Used': 'उपयोग',
      'Pickup Date': 'पिकअप तारीख',
      'Driver': 'ड्राइवर',
      'Destination': 'गंतव्य',
      'Pickup Route': 'पिकअप मार्ग',
      'Total Distance': 'कुल दूरी',
      'Duration': 'अवधि',
      'Fuel': 'ईंधन',
      'Farms': 'खेत',
      'Recommended for': 'अनुशंसित',
      'Combined Quantity': 'संयुक्त मात्रा',
      'Individual Average Offer': 'व्यक्तिगत औसत ऑफर',
      'Group Negotiated Offer': 'समूह तय ऑफर',
      'Potential Extra Revenue': 'संभावित अतिरिक्त राजस्व',
      'Crop Status': 'फसल स्थिति',
      'Analysis': 'विश्लेषण',
      'Best Window': 'श्रेष्ठ समय',
      'Best': 'श्रेष्ठ',
      'Clear': 'साफ',
      'Light Rain': 'हल्की बारिश',
      'Heavy Rain': 'तेज बारिश',
      'Cloudy': 'बादल',
      'Good': 'अच्छा',
      'Highest forecast price': 'सबसे ऊंचा अनुमानित भाव',
      'on': 'को',
      'workers': 'मजदूर',
      'hours': 'घंटे',
      'estimated': 'अनुमानित',
      'harvest plan': 'कटाई योजना',
      'Harvest date': 'कटाई तारीख',
      'AI suggested': 'AI सुझाव',
      'Buyer pickup': 'खरीदार पिकअप',
      'Cooperative buyer pool': 'सहकारी खरीदार पूल',
      'Buyer pickup slot confirmed.': 'खरीदार पिकअप स्लॉट पक्का हुआ।',
      'Detected Disease': 'पहचाना गया रोग',
      'Symptoms': 'लक्षण',
      'Possible Cause': 'संभावित कारण',
      'Recommended Action': 'अनुशंसित कार्रवाई',
      'Treatment': 'उपचार',
      'Prevention': 'बचाव',
      'Save Report': 'रिपोर्ट सेव करें',
      'Disease report saved in demo reports.': 'रोग रिपोर्ट डेमो रिपोर्ट में सेव हुई।',
      'Take or upload a crop photo to get disease guidance.': 'रोग मार्गदर्शन के लिए फसल फोटो लें या अपलोड करें।',
      'Which fertilizer should I use?': 'कौन सा उर्वरक इस्तेमाल करूं?',
      'Why are my tomato leaves yellow?': 'मेरे टमाटर के पत्ते पीले क्यों हैं?',
      'When should I harvest?': 'कटाई कब करूं?',
      'Tell me government schemes.': 'सरकारी योजनाएं बताएं।',
      'Give crop advice for my farm.': 'मेरे खेत के लिए फसल सलाह दें।',
      'Namaste. How can I help with your farm today?': 'नमस्ते। आज मैं आपके खेत में कैसे मदद कर सकता हूं?',
      'Application checklist opened for': 'आवेदन चेकलिस्ट खुली',
      'saved for follow-up.': 'फॉलो-अप के लिए सेव हुआ।',
      'Search farm, crop, buyer, scheme, order, AI, market': 'खेत, फसल, खरीदार, योजना, ऑर्डर, AI, बाजार खोजें',
      'Search AgroPredict': 'AgroPredict खोजें',
      'Find farms, crops, buyers, schemes, orders, AI conversation and market data.': 'खेत, फसलें, खरीदार, योजनाएं, ऑर्डर, AI बातचीत और बाजार डेटा खोजें।',
      'Try Tomato': 'टमाटर आजमाएं',
      'No notifications': 'कोई सूचना नहीं',
      'AI, weather, market, harvest, transport, payment, cooperative, and scheme alerts will appear here.': 'AI, मौसम, बाजार, कटाई, परिवहन, भुगतान, सहकारी और योजना अलर्ट यहां दिखेंगे।',
      'Refresh': 'रिफ्रेश',
      'Total Sales Orders': 'कुल बिक्री ऑर्डर',
      'Quantity Sold': 'बिकी मात्रा',
      'Average Selling Price': 'औसत बिक्री भाव',
      'Best Buyer': 'सर्वश्रेष्ठ खरीदार',
      'VERY HIGH': 'बहुत ऊंचा',
      'Available Balance': 'उपलब्ध बैलेंस',
      'Pending Payments': 'लंबित भुगतान',
      'Expected Revenue': 'अपेक्षित राजस्व',
      'ROI': 'ROI',
      'Insurance Status': 'बीमा स्थिति',
      'Active': 'सक्रिय',
    },
    'mr': {
      'languageTitle': 'अ‍ॅप भाषा निवडा',
      'languageSubtitle': 'ऑनबोर्डिंगपूर्वी भाषा निवडा. नंतर प्रोफाइलमधून बदलता येईल.',
      'continue': 'पुढे चला',
      'home': 'होम',
      'farm': 'शेत',
      'market': 'बाजार',
      'profile': 'प्रोफाइल',
      'goodMorning': 'शुभ प्रभात',
      'quickActions': 'जलद कृती',
      'harvest': 'कापणी',
      'schemes': 'योजना',
      'reports': 'अहवाल',
      'language': 'भाषा',
      'profileSettings': 'प्रोफाइल आणि सेटिंग',
    },
    'gu': {
      'languageTitle': 'એપ ભાષા પસંદ કરો',
      'languageSubtitle': 'ઓનબોર્ડિંગ પહેલાં ભાષા પસંદ કરો. પછી પ્રોફાઇલમાંથી બદલી શકો છો.',
      'continue': 'આગળ વધો',
      'home': 'હોમ',
      'farm': 'ખેતર',
      'market': 'બજાર',
      'profile': 'પ્રોફાઇલ',
      'goodMorning': 'સુપ્રભાત',
      'quickActions': 'ઝડપી ક્રિયાઓ',
      'harvest': 'કાપણી',
      'schemes': 'યોજનાઓ',
      'reports': 'રિપોર્ટ',
      'language': 'ભાષા',
      'profileSettings': 'પ્રોફાઇલ અને સેટિંગ',
    },
    'ta': {
      'languageTitle': 'ஆப் மொழியை தேர்வு செய்யவும்',
      'languageSubtitle': 'ஆன்போர்டிங் முன் மொழியை தேர்வு செய்யவும். பிறகு ப்ரொஃபைலில் மாற்றலாம்.',
      'continue': 'தொடரவும்',
      'home': 'முகப்பு',
      'farm': 'பண்ணை',
      'market': 'சந்தை',
      'profile': 'சுயவிவரம்',
      'goodMorning': 'காலை வணக்கம்',
      'quickActions': 'விரைவு செயல்கள்',
      'harvest': 'அறுவடை',
      'schemes': 'திட்டங்கள்',
      'reports': 'அறிக்கைகள்',
      'language': 'மொழி',
      'profileSettings': 'சுயவிவரம் மற்றும் அமைப்புகள்',
    },
    'te': {
      'languageTitle': 'యాప్ భాషను ఎంచుకోండి',
      'languageSubtitle': 'ఆన్‌బోర్డింగ్‌కు ముందు భాషను ఎంచుకోండి. తర్వాత ప్రొఫైల్‌లో మార్చవచ్చు.',
      'continue': 'కొనసాగించండి',
      'home': 'హోమ్',
      'farm': 'పొలం',
      'market': 'మార్కెట్',
      'profile': 'ప్రొఫైల్',
      'goodMorning': 'శుభోదయం',
      'quickActions': 'త్వరిత చర్యలు',
      'harvest': 'పంట కోత',
      'schemes': 'పథకాలు',
      'reports': 'రిపోర్టులు',
      'language': 'భాష',
      'profileSettings': 'ప్రొఫైల్ మరియు సెట్టింగులు',
    },
    'kn': {
      'languageTitle': 'ಆಪ್ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'languageSubtitle': 'ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಮೊದಲು ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ. ನಂತರ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಬದಲಾಯಿಸಬಹುದು.',
      'continue': 'ಮುಂದುವರಿಸಿ',
      'home': 'ಹೋಮ್',
      'farm': 'ಫಾರ್ಮ್',
      'market': 'ಮಾರುಕಟ್ಟೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'goodMorning': 'ಶುಭೋದಯ',
      'quickActions': 'ತ್ವರಿತ ಕ್ರಮಗಳು',
      'harvest': 'ಕೊಯ್ಲು',
      'schemes': 'ಯೋಜನೆಗಳು',
      'reports': 'ವರದಿಗಳು',
      'language': 'ಭಾಷೆ',
      'profileSettings': 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್',
    },
    'pa': {
      'languageTitle': 'ਐਪ ਭਾਸ਼ਾ ਚੁਣੋ',
      'languageSubtitle': 'ਆਨਬੋਰਡਿੰਗ ਤੋਂ ਪਹਿਲਾਂ ਭਾਸ਼ਾ ਚੁਣੋ। ਬਾਅਦ ਵਿੱਚ ਪ੍ਰੋਫਾਈਲ ਤੋਂ ਬਦਲ ਸਕਦੇ ਹੋ।',
      'continue': 'ਜਾਰੀ ਰੱਖੋ',
      'home': 'ਹੋਮ',
      'farm': 'ਖੇਤ',
      'market': 'ਮਾਰਕੀਟ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'goodMorning': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
      'quickActions': 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ',
      'harvest': 'ਕਟਾਈ',
      'schemes': 'ਯੋਜਨਾਵਾਂ',
      'reports': 'ਰਿਪੋਰਟਾਂ',
      'language': 'ਭਾਸ਼ਾ',
      'profileSettings': 'ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਸੈਟਿੰਗ',
    },
    'es': {
      'languageTitle': 'Elige el idioma',
      'languageSubtitle': 'Puedes cambiarlo después desde Perfil.',
      'continue': 'Continuar',
      'home': 'Inicio',
      'farm': 'Granja',
      'market': 'Mercado',
      'profile': 'Perfil',
      'goodMorning': 'Buenos días',
      'quickActions': 'Acciones rápidas',
      'language': 'Idioma',
      'profileSettings': 'Perfil y ajustes',
    },
    'fr': {
      'languageTitle': 'Choisir la langue',
      'languageSubtitle': 'Vous pourrez la changer depuis Profil.',
      'continue': 'Continuer',
      'home': 'Accueil',
      'farm': 'Ferme',
      'market': 'Marché',
      'profile': 'Profil',
      'goodMorning': 'Bonjour',
      'quickActions': 'Actions rapides',
      'language': 'Langue',
      'profileSettings': 'Profil et réglages',
    },
  };

  String t(String key) {
    final code = locale.languageCode;
    final translated = _localized[code]?[key];
    if (translated != null) return translated;
    if (const {'hi', 'mr', 'gu', 'ta', 'te', 'kn', 'pa', 'bn', 'ml', 'or'}.contains(code)) {
      return _localized['hi']?[key] ?? _localized['en']?[key] ?? key;
    }
    return _localized['en']?[key] ?? key;
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
